# encoding: utf8

# ROI Colors.

# Target colors:
gtv = 'Red'
ctv = 'Pink'
ptv = '0, 128, 255'
ptv_breast = 'LightSkyBlue'
ctv_alt = 'LightPink'
ctv_low = 'Pink'
ctv_med = 'Violet'
ctv_high = 'Salmon'
ptv_low = '0, 64, 128'
ptv_med = '0, 128, 255'
ptv_high = '0, 0, 128'

# OAR colors:
brain = 'Yellow'
brainstem = 'Khaki'
eye = 'DeepSkyBlue'
lens = 'DarkTurquoise'
optic_nrv = 'SaddleBrown'
chiasma = 'Brown'
lacrimal = 'DarkBlue'
cochlea = 'Violet'
hippocampus = 'Sienna'
nasal_cavity = 'OliveDrab'
oral_cavity = 'Olive'
parotid = 'Orange'
submand = 'DarkOrange'
thyroid = 'Teal'
spinal_cord = 'Blue'
spinal_canal = 'Blue'
heart = 'Maroon'
lungs = 'Green'
lung = 'Lime'
kidney = 'LightSalmon'
kidneys = 'LightSalmon'
bowel_space = 'SandyBrown'
bladder = 'Yellow'
rectum = 'SaddleBrown'
esophagus = 'Orange'
pituitary =  'Orange'
artery1 = 'Maroon'
artery2 = 'Red'
vein1 = 'Navy'
vein2 = 'Blue'
muscle = 'Darkcyan'
contralat = '128, 128, 255'
contralat_draft = '255, 192, 203'
lad = 'Red'
caput ='Teal'
breast_draft = 'Salmon'
level4 = 'Sienna'
level3 = 'Navy'
level2 = 'Maroon'
level1 = 'Khaki'
level = 'DarkSlateGray'
imn = 'Maroon'
clips = 'Magenta'
pelvic_nodes = 'Magenta'
prostate = 'DeepPink'
prostate_bed = 'DeepPink'
vesicles = 'Violet'
femoral = 'ForestGreen'
bowel_contrast = 'Gray'
dorso_rectum = 'SaddleBrown'
seed = 'Blue'
wall = '128, 128, 128'
chestwall = 'Olive'
trachea = 'Teal'
stomach = 'SandyBrown'
pancreas = 'Coral'
spleen = 'Crimson'
liver = 'Khaki'
rib = 'Navy'
ribs = 'MidnightBlue'
main_bronchus = 'Green'
skin = 'White'
cauda = 'Blue'
small_bowel = 'SandyBrown'
colon = 'SandyBrown'
brachial = 'Orange'
brainstem_core = 'Khaki'
brainstem_surface = 'DarkOrange'
cornea = 'Yellow'
retina = 'OrangeRed'
urethra = 'Orange'

# PRVs:
prv = '128, 128, 128'
other_ptv = '0, 128, 128'

# External:
external = '255, 173, 91'

# Support
couch = 'Blue'

# Other:
mask_ptv = 'Black'
prosthesis = '255, 173, 91'

# POIs:
ref = 'Yellow'
iso = '98, 184, 234'
