# encoding: utf8

# Import local files:
import colors as COLORS
import margins as MARGINS
import roi as ROI

# Common ROIs:
# External:
external = ROI.ROI('External', 'External', COLORS.external)
body = ROI.ROI('Body', 'Organ', COLORS.external)
# Support:
couch = ROI.ROI('Couch', 'Support', COLORS.couch)


# Empty organ ROIs:
a_pulmonary = ROI.ROI('A_Pulmonary', 'Organ', COLORS.a_pulmonary)
anorectum = ROI.ROI('Anorectum', 'Organ', COLORS.rectum)
bone = ROI.ROI('Bone', 'Organ', COLORS.bone_color1)
bowel_small = ROI.ROI('BowelSmall','Organ', COLORS.small_bowel)
bowel_space = ROI.ROI('BowelBag', 'Organ', COLORS.bowel_space) # FIXME: Remove this and replace with bowel_bag_draft/bowel_bag_derived
bronchi_lobar_l = ROI.ROI('BronchiLobar_L','Organ', COLORS.bronchi_lobar)
bronchi_lobar_r = ROI.ROI('BronchiLobar_R','Organ', COLORS.bronchi_lobar)
chestwall = ROI.ROI('Chestwall', 'Organ', COLORS.chestwall)
colon = ROI.ROI('Colon','Organ', COLORS.colon)
cornea_l = ROI.ROI('Cornea_L', 'Organ', COLORS.cornea) 
cornea_r = ROI.ROI('Cornea_R', 'Organ', COLORS.cornea)
hippocampus_l = ROI.ROI('Hippocampus_L','Organ', COLORS.hippocampus)
hippocampus_r = ROI.ROI('Hippocampus_R','Organ', COLORS.hippocampus)
levator_ani = ROI.ROI('LevatorAni', 'Organ', COLORS.levator_ani)
nasal_cavity = ROI.ROI('NasalCavity', 'Organ', COLORS.nasal_cavity)
prostate_bed = ROI.ROI('SurgicalBed', 'Ctv', COLORS.prostate_bed)
retina_l = ROI.ROI('Retina_L', 'Organ', COLORS.retina) 
retina_r = ROI.ROI('Retina_R', 'Organ', COLORS.retina)
rib_x_l = ROI.ROI('Ribx_L','Organ', COLORS.rib)
rib_x_r = ROI.ROI('Ribx_R','Organ', COLORS.rib)
rib_y_l = ROI.ROI('Riby_L','Organ', COLORS.rib)
rib_y_r = ROI.ROI('Riby_R','Organ', COLORS.rib)
ribs = ROI.ROI('Ribs','Organ', COLORS.ribs)
spinal_cord = ROI.ROI('SpinalCord', 'Organ', COLORS.spinal_cord)
urethra = ROI.ROI('Urethra', 'Organ', COLORS.urethra)
uterus = ROI.ROI('Uterus', 'Organ', COLORS.uterus)
v_pulmonary = ROI.ROI('V_Pulmonary', 'Organ', COLORS.v_pulmonary)


# Undefined / Other ROIs
marker1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
marker2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
marker3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
marker4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)
markers = ROI.ROI('Markers', 'Marker', COLORS.clips)
prosthesis = ROI.ROI('Prosthesis','Undefined', COLORS.prosthesis)
prosthesis_l = ROI.ROI('Prosthesis_L','Undefined', COLORS.prosthesis)
prosthesis_r = ROI.ROI('Prosthesis_R','Undefined', COLORS.prosthesis)
seed1 = ROI.ROI('Marker1', 'Marker', COLORS.seed)
seed2 = ROI.ROI('Marker2', 'Marker', COLORS.seed)
seed3 = ROI.ROI('Marker3', 'Marker', COLORS.seed)
seed4 = ROI.ROI('Marker4', 'Marker', COLORS.seed)


# Target volumes:
gtv = ROI.ROI('GTV', 'Gtv', COLORS.gtv)
ctv = ROI.ROIExpanded('CTV', 'Ctv', COLORS.ctv, gtv, margins = MARGINS.uniform_5mm_expansion)
ptv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, ctv, margins = MARGINS.uniform_5mm_expansion)
ctv_ext = ROI.ROIAlgebra('CTV', 'Ctv', COLORS.ctv, sourcesA = [gtv], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.uniform_5mm_expansion, marginsB = MARGINS.uniform_5mm_contraction)
ctv_underived = ROI.ROI('CTV', 'Ctv', COLORS.ctv)
igtv = ROI.ROI('IGTV', 'Gtv', COLORS.gtv)
igtv1 = ROI.ROI('IGTV1', 'Gtv', COLORS.gtv)
igtv2 = ROI.ROI('IGTV2', 'Gtv', COLORS.gtv)
igtv3 = ROI.ROI('IGTV3', 'Gtv', COLORS.gtv)
ictv = ROI.ROIExpanded('ICTV', 'Ctv', COLORS.ctv, igtv, margins = MARGINS.uniform_5mm_expansion)
ictv1 = ROI.ROIExpanded('ICTV1', 'Ctv', COLORS.ctv, igtv1, margins = MARGINS.uniform_5mm_expansion)
ictv2 = ROI.ROIExpanded('ICTV2', 'Ctv', COLORS.ctv, igtv2, margins = MARGINS.uniform_5mm_expansion)
ictv3 = ROI.ROIExpanded('ICTV3', 'Ctv', COLORS.ctv, igtv3, margins = MARGINS.uniform_5mm_expansion)
iptv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, ictv, margins = MARGINS.uniform_5mm_expansion)
iptv_gtv = ROI.ROIExpanded('PTV', 'Ptv', COLORS.ptv, igtv, margins = MARGINS.uniform_5mm_expansion)
iptv1 = ROI.ROIExpanded('PTV1', 'Ptv', COLORS.ptv, ictv1, margins = MARGINS.uniform_5mm_expansion)
iptv2 = ROI.ROIExpanded('PTV2', 'Ptv', COLORS.ptv, ictv2, margins = MARGINS.uniform_5mm_expansion)
iptv3 = ROI.ROIExpanded('PTV3', 'Ptv', COLORS.ptv, ictv3, margins = MARGINS.uniform_5mm_expansion)
gtv_p = ROI.ROI('GTVp','Gtv', COLORS.gtv)
gtv_n = ROI.ROI('GTVn','Gtv', COLORS.gtv)
gtv_n1 = ROI.ROI('GTVn','Gtv', COLORS.gtv)
ctv_e = ROI.ROI('CTVe','Ctv', COLORS.ctv_med)
ptv_e = ROI.ROI('PTVe','Ptv', COLORS.ptv)
gtv_groin_l = ROI.ROI('GTV_Groin_L','Gtv', COLORS.gtv)
gtv_groin_r = ROI.ROI('GTV_Groin_R','Gtv', COLORS.gtv)
ctv_groin_l = ROI.ROI('CTV_Groin_L','Ctv', COLORS.ctv_med)
ctv_groin_r = ROI.ROI('CTV_Groin_R','Ctv', COLORS.ctv_med)
ptv_groin_l = ROI.ROI('PTV_Groin_L','Ptv', COLORS.ptv)
ptv_groin_r = ROI.ROI('PTV_Groin_R','Ptv', COLORS.ptv)
ctv_p = ROI.ROI('CTVp', 'Ctv', COLORS.ctv)
ctv_n = ROI.ROI('CTVn','Ctv', COLORS.ctv)
igtv_p = ROI.ROI('IGTVp','Gtv', COLORS.gtv)
igtv_n = ROI.ROI('IGTVn','Gtv', COLORS.gtv)
ictv_p = ROI.ROI('ICTVp', 'Ctv', COLORS.ctv)
ictv_n = ROI.ROI('ICTVn', 'Ctv', COLORS.ctv)
gtv1 = ROI.ROI('GTV1', 'Gtv', COLORS.gtv)
gtv2 = ROI.ROI('GTV2', 'Gtv', COLORS.gtv)
gtv3 = ROI.ROI('GTV3', 'Gtv', COLORS.gtv)
gtv4 = ROI.ROI('GTV4', 'Gtv', COLORS.gtv)
ctv1 = ROI.ROI('CTV1', 'Ctv', COLORS.ctv)
ctv2 = ROI.ROI('CTV2', 'Ctv', COLORS.ctv)
ctv3 = ROI.ROI('CTV3', 'Ctv', COLORS.ctv)
ctv4 = ROI.ROI('CTV4', 'Ctv', COLORS.ctv)
gtv_sb = ROI.ROI('GTVsb', 'Gtv', COLORS.gtv)
ctv_sb = ROI.ROI('CTVsb', 'Ctv', COLORS.ctv)
vb = ROI.ROI('VB','Ctv', COLORS.ctv_med)
ctv_l = ROI.ROI('CTV_L', 'Ctv', COLORS.ctv)
ctv_r = ROI.ROI('CTV_R', 'Ctv', COLORS.ctv)
ptvc_l = ROI.ROI('PTVc_L', 'Ptv', COLORS.ptv)
ptvc_r = ROI.ROI('PTVc_R', 'Ptv', COLORS.ptv)


# ROIs for optimization:
z_water =  ROI.ROI('zWater', 'Undefined', COLORS.other_ptv)
z_heart =  ROI.ROI('zHeart', 'Undefined', COLORS.heart)
z_esophagus =  ROI.ROI('zEsophagus', 'Undefined', COLORS.esophagus)
z_bladder = ROI.ROI('zBladder','Undefined', COLORS.bladder)
z_spc_bowel = ROI.ROI('zBowelBag','Undefined', COLORS.bowel_space)
z_rectum = ROI.ROI('zRectum', 'Undefined', COLORS.rectum)
z_ptv_77_wall = ROI.ROI('zPTV_77_Wall', 'Undefined', COLORS.wall)
z_ptv_70_77_wall = ROI.ROI('zPTV_70+77_Wall', 'Undefined', COLORS.wall)
z_ptv_67_5_wall = ROI.ROI('zPTV_67.5_Wall', 'Undefined', COLORS.wall)
z_ptv_62_5_67_5_wall = ROI.ROI('zPTV_62.5+67.5_Wall', 'Undefined', COLORS.wall)
z_ptv_50_62_5_67_5_wall = ROI.ROI('zPTV_50+62.5+67.5_Wall', 'Undefined', COLORS.wall)
z_ptv_60_wall = ROI.ROI('zPTV_60_Wall', 'Undefined', COLORS.wall)
z_ptv_50_wall = ROI.ROI('zPTV_50_Wall', 'Undefined', COLORS.wall)
z_ptv_47_50_wall = ROI.ROI('zPTV_47+50_Wall', 'Undefined', COLORS.wall)
z_ptv_57_60_wall = ROI.ROI('zPTV_57+60_Wall', 'Undefined', COLORS.wall)
z_ptv_70_wall = ROI.ROI('zPTV_70_Wall', 'Undefined', COLORS.wall)
z_ptv_62_5_wall = ROI.ROI('zPTV_62.5_Wall', 'Undefined', COLORS.wall)
z_ptv_56_temp = ROI.ROI('zPTV_56_Temp', 'Undefined', COLORS.wall)
z_ptv_56_wall = ROI.ROI('zPTV_56_Wall', 'Undefined', COLORS.wall)
z_ptv_50_temp = ROI.ROI('zPTV_50_Temp', 'Undefined', COLORS.wall)
z_ptv_50_wall = ROI.ROI('zPTV_50_Wall', 'Undefined', COLORS.wall)
z_ptv_wall = ROI.ROI('zPTV_Wall', 'Undefined', COLORS.wall)
z_ptv1_wall = ROI.ROI('zPTV1_Wall', 'Undefined', COLORS.wall)
z_ptv2_wall = ROI.ROI('zPTV2_Wall', 'Undefined', COLORS.wall)
z_ptv3_wall = ROI.ROI('zPTV3_Wall', 'Undefined', COLORS.wall)
z_ptv4_wall = ROI.ROI('zPTV4_Wall', 'Undefined', COLORS.wall)
ctv_oars = ROI.ROI('zCTV-OARs', 'Ctv', COLORS.ctv)
ptv_oars = ROI.ROI('zPTV-OARs', 'Ptv', COLORS.ptv)
ptv_and_oars = ROI.ROI('zPTV_AND_OARs', 'Ptv', COLORS.other_ptv)


# Substitute ROI objects (only used for naming):
ptv_semves = ROI.ROI('PTV_SeminalVes', 'Ptv', COLORS.ptv_med)
# Prostate 56/66/70/77:
ptv_77 = ROI.ROI('PTV_77', 'Ptv', COLORS.ptv_high)
ptv_70 = ROI.ROI('PTV_70', 'Ptv', COLORS.ptv_med)
ptv_70_sib = ROI.ROI('PTV!_70', 'Ptv', COLORS.ptv_med)
ctv_77 = ROI.ROI('CTV_77', 'Ctv', COLORS.ctv_high)
ctv_70 = ROI.ROI('CTV_70', 'Ctv', COLORS.ctv_med)
ctv_70_sib = ROI.ROI('CTV!_70', 'Ctv', COLORS.ctv_med)
ptv_66 = ROI.ROI('PTV!_66', 'Ptv', COLORS.ptv_med)
ctv_66 = ROI.ROI('CTV!_66', 'Ctv', COLORS.ctv_med)
ptv_56 = ROI.ROI('PTV!_56', 'Ptv', COLORS.ptv_low)
ctv_56 = ROI.ROI('CTV!_56', 'Ctv', COLORS.ctv_low)
ptv_70_77 = ROI.ROI('PTV_70+77', 'Ptv', COLORS.ptv_low)
ctv_70_77 = ROI.ROI('CTV_70+77', 'Ctv', COLORS.ctv_low)
ptv_56_70_77 = ROI.ROI('PTV_56+70+77', 'Ptv', COLORS.ptv_low)
ptv_56_70 = ROI.ROI('PTV_56+70', 'Ptv', COLORS.ptv_low)
# Prostate 50/60/62.5/67.5:
ptv_67_5 = ROI.ROI('PTV_67.5', 'Ptv', COLORS.ptv_high)
ptv_62_5 = ROI.ROI('PTV_62.5', 'Ptv', COLORS.ptv_med)
ptv_62_5_sib = ROI.ROI('PTV!_62.5', 'Ptv', COLORS.ptv_med)
ctv_67_5 = ROI.ROI('CTV_67.5', 'Ctv', COLORS.ctv_high)
ctv_62_5 = ROI.ROI('CTV_62.5', 'Ctv', COLORS.ctv_med)
ctv_62_5_sib = ROI.ROI('CTV!_62.5', 'Ctv', COLORS.ctv_med)
ptv__60 = ROI.ROI('PTV!_60', 'Ptv', COLORS.ptv_med)
ctv__60 = ROI.ROI('CTV!_60', 'Ctv', COLORS.ctv_med)
ptv__50 = ROI.ROI('PTV!_50', 'Ptv', COLORS.ptv_low)
ctv__50 = ROI.ROI('CTV!_50', 'Ctv', COLORS.ctv_low)
ptv_62_5_67_5 = ROI.ROI('PTV_62.5+67.5', 'Ptv', COLORS.ptv_low)
ctv_62_5_67_5 = ROI.ROI('CTV_62.5+67.5', 'Ctv', COLORS.ctv_low)
ptv_50_62_5_67_5 = ROI.ROI('PTV_50+62.5+67.5', 'Ptv', COLORS.ptv_low)
ptv_50_62_5 = ROI.ROI('PTV_50+62.5', 'Ptv', COLORS.ptv_low)
# Prostate 57/60:
ptv_57_60 = ROI.ROI('PTV_57+60', 'Ptv', COLORS.ptv_low)
ctv_57_60 = ROI.ROI('CTV_57+60', 'Ctv', COLORS.ctv_low)
ptv_60 = ROI.ROI('PTV_60', 'Ptv', COLORS.ptv_high)
ctv_60 = ROI.ROI('CTV_60', 'Ctv', COLORS.ctv_high)
ptv_57 = ROI.ROI('PTV!_57', 'Ptv', COLORS.ptv_med)
ctv_57 = ROI.ROI('CTV!_57', 'Ctv', COLORS.ctv_med)
# Prostate 36.25/40:
ctv_40 = ROI.ROI('CTV_40', 'Ctv', COLORS.ctv_high)
ptv_36_25 = ROI.ROI('PTV_36.25', 'Ptv', COLORS.ptv_high)
# Breast:
ptv_pc =  ROI.ROI('PTVpc', 'Ptv', COLORS.ptv)
ptv_pc_l =  ROI.ROI('PTVpc_L', 'Ptv', COLORS.ptv)
ptv_pc_r =  ROI.ROI('PTVpc_R', 'Ptv', COLORS.ptv)
ptv_p = ROI.ROI('PTVp', 'Ptv', COLORS.ptv)
ptv_n =  ROI.ROI('PTVn', 'Ptv', COLORS.ptv)
ptv_nc =  ROI.ROI('PTVnc', 'Ptv', COLORS.ptv)
ptv1 =  ROI.ROI('PTV1', 'Ptv', COLORS.ptv)
ptv2 =  ROI.ROI('PTV2', 'Ptv', COLORS.ptv)
ptv3 =  ROI.ROI('PTV3', 'Ptv', COLORS.ptv)
ptv4 =  ROI.ROI('PTV4', 'Ptv', COLORS.ptv)
ptv_c = ROI.ROI('PTVc', 'Ptv', COLORS.ptv)
ptv_sb = ROI.ROI('PTVsb', 'Ptv', COLORS.ptv)
ptv_sbc = ROI.ROI('PTVsbc', 'Ptv', COLORS.ptv)
# Rectum:
ctv_47_50 =  ROI.ROI('CTV_47+50', 'Ctv', COLORS.ctv_low)
ptv_47_50 =  ROI.ROI('PTV_47+50', 'Ptv', COLORS.ptv_low)
ptv_50 = ROI.ROI('PTV_50', 'Ptv', COLORS.ptv_high)
ptv_50c = ROI.ROI('PTV_50c', 'Ptv', COLORS.ptv_high)
ctv_50 = ROI.ROI('CTV_50', 'Ctv', COLORS.ctv_high)
ctv_47 =  ROI.ROI('CTV!_47', 'Ctv', COLORS.ctv_low)
ctv_47_tot =  ROI.ROI('CTV_47', 'Ctv', COLORS.ctv_low)
ptv_47 =  ROI.ROI('PTV!_47', 'Ptv', COLORS.ptv_med)
ptv_47_tot =  ROI.ROI('PTV_47', 'Ptv', COLORS.ptv_med)
ptv_47c =  ROI.ROI('PTV!_47c', 'Ptv', COLORS.ptv_med)


# Miscellaneous:
brain_gtv = ROI.ROI('Brain-GTV','Organ', COLORS.brain)
brain_ptv = ROI.ROI('Brain-PTV','Organ', COLORS.other_ptv)
lungs_gtv = ROI.ROI('Lungs-GTV', 'Organ', COLORS.lungs)
lungs_ctv = ROI.ROI('Lungs-CTV', 'Organ', COLORS.lungs)
ctv_p_ctv_sb = ROI.ROI('CTVp-CTVsb', 'Ctv', COLORS.ctv)
ctv_ctv_sb = ROI.ROI('CTV-CTVsb', 'Ctv', COLORS.ctv)
ctv_p_ptv_sbc = ROI.ROI('CTVp-PTVsbc', 'Ctv', COLORS.ctv)
ctv_ptv_sbc = ROI.ROI('CTV-PTVsbc', 'Ctv', COLORS.ctv)
ptv_pc_ptv_sbc = ROI.ROI('PTVpc-PTVsbc', 'Ptv', COLORS.ptv)
ptv_c_ptv_sbc = ROI.ROI('PTVc-PTVsbc', 'Ptv', COLORS.ptv)
ptv_gtv = ROI.ROI('PTV-GTV', 'Ptv', COLORS.ptv_med)
ptv_spinal = ROI.ROI('PTV-SpinalCord_PRV', 'Ptv', COLORS.ptv_med)
mask_ptv = ROI.ROI('Mask_PTV','Undefined', COLORS.mask_ptv)
mask_ptv1 = ROI.ROI('Mask_PTV1','Undefined', COLORS.mask_ptv)
mask_ptv2 = ROI.ROI('Mask_PTV2','Undefined', COLORS.mask_ptv)
mask_ptv3 = ROI.ROI('Mask_PTV3','Undefined', COLORS.mask_ptv)
box = ROI.ROI('zBox','Undefined', COLORS.mask_ptv)
box1 = ROI.ROI('zBox1','Undefined', COLORS.mask_ptv)
box_l = ROI.ROI('zBox_L','Undefined', COLORS.mask_ptv)
box_r = ROI.ROI('zBox_R','Undefined', COLORS.mask_ptv)
box3 = ROI.ROI('zBox3','Undefined', COLORS.mask_ptv)
box4 = ROI.ROI('zBox4','Undefined', COLORS.mask_ptv)


# DLS ROIs:
a_aortic_arch = ROI.ROIDLS('A_AorticArch', 'Organ', COLORS.artery_color4, 'RSL DLS CT', lib_name = 'A_Aorta_arcus')
a_ascending_aorta = ROI.ROIDLS('A_AscendingAorta', 'Organ', COLORS.artery_color3, 'RSL DLS CT', lib_name = 'A_Aorta_Ascen')
a_brachiocephalic = ROI.ROIDLS('A_Brachiocephalic', 'Organ', COLORS.artery_color5, 'RSL DLS CT')
a_carotid_l = ROI.ROIDLS('A_Carotid_L', 'Organ', COLORS.artery_color6, 'RSL DLS CT')
a_carotid_r = ROI.ROIDLS('A_Carotid_R', 'Organ', COLORS.artery_color6, 'RSL DLS CT')
a_common_iliac_l = ROI.ROIDLS('A_CommonIliac_L', 'Organ', COLORS.artery_color2, 'Alesund Male Pelvic CT')
a_common_iliac_r = ROI.ROIDLS('A_CommonIliac_R', 'Organ', COLORS.artery_color2, 'Alesund Male Pelvic CT')
a_descending_aorta = ROI.ROIDLS('A_DescendingAorta', 'Organ', COLORS.artery_color1, 'Alesund Male Pelvic CT')
a_external_iliac_l = ROI.ROIDLS('A_ExternalIliac_L', 'Organ', COLORS.artery_color4, 'Alesund Male Pelvic CT')
a_external_iliac_r = ROI.ROIDLS('A_ExternalIliac_R', 'Organ', COLORS.artery_color4, 'Alesund Male Pelvic CT')
a_internal_iliac_l = ROI.ROIDLS('A_InternalIliac_L', 'Organ', COLORS.artery_color3, 'Alesund Male Pelvic CT')
a_internal_iliac_r = ROI.ROIDLS('A_InternalIliac_R', 'Organ', COLORS.artery_color3, 'Alesund Male Pelvic CT')
a_lad = ROI.ROIDLS('A_LAD','Organ', COLORS.lad, 'RSL DLS CT')
a_subclavian_l = ROI.ROIDLS('A_Subclavian_L', 'Organ', COLORS.artery_color3, 'RSL DLS CT')
a_subclavian_r = ROI.ROIDLS('A_Subclavian_R', 'Organ', COLORS.artery_color3, 'RSL DLS CT')
anal_canal = ROI.ROIDLS('AnalCanal','Organ', COLORS.anal_canal, 'Alesund Male Pelvic CT')
bladder = ROI.ROIDLS('Bladder', 'Organ', COLORS.bladder, 'RSL DLS CT')
bladder_draft = ROI.ROIDLS('Bladder_Draft', 'Organ', COLORS.bladder, 'RSL DLS CT', lib_name = 'Bladder')
bowel_bag_draft = ROI.ROIDLS('BowelBag_Draft', 'Other', COLORS.bowel_space, 'Alesund Male Pelvic CT', lib_name = 'BowelBag')
brachial_plexus_l = ROI.ROIDLS('BrachialPlexus_L','Organ', COLORS.brachial_plexus, 'RSL DLS CT', lib_name = 'Brachial_Plexus_L')
brachial_plexus_r = ROI.ROIDLS('BrachialPlexus_R','Organ', COLORS.brachial_plexus, 'RSL DLS CT', lib_name = 'Brachial_Plexus_R')
brain = ROI.ROIDLS('Brain', 'Organ', COLORS.brain, 'RSL DLS CT')
brainstem = ROI.ROIDLS('Brainstem', 'Organ', COLORS.brainstem, 'RSL DLS CT')
breast_l_draft = ROI.ROIDLS('Breast_L_Draft', 'Organ', COLORS.contralat_draft, 'RSL DLS CT', lib_name = 'IpsilateralBreast_L')
breast_r_draft = ROI.ROIDLS('Breast_R_Draft', 'Organ', COLORS.contralat_draft, 'RSL DLS CT', lib_name = 'IpsilateralBreast_R')
breast_string_l = ROI.ROIDLS('BreastString_L', 'Marker', COLORS.breast_string, 'St. Olavs-Alesund Breast CT')
breast_string_r = ROI.ROIDLS('BreastString_R', 'Marker', COLORS.breast_string, 'St. Olavs-Alesund Breast CT')
bronchus_intermedius = ROI.ROIDLS('BronchusIntermedius','Organ', COLORS.bronchus_intermedius, 'RSL DLS CT', lib_name = 'Bronchus_InterM')
bronchus_main_l = ROI.ROIDLS('BronchusMain_L','Organ', COLORS.main_bronchus, 'RSL DLS CT', lib_name = 'Bronchus_Main_L')
bronchus_main_r = ROI.ROIDLS('BronchusMain_R','Organ', COLORS.main_bronchus, 'RSL DLS CT', lib_name = 'Bronchus_Main_R')
carina = ROI.ROIDLS('Carina','Organ', COLORS.carina, 'RSL DLS CT')
cauda_equina = ROI.ROIDLS('CaudaEquina', 'Organ', COLORS.cauda, 'Alesund Male Pelvic CT')
clips_l = ROI.ROIDLS('Clips_L', 'Marker', COLORS.clips, 'St. Olavs-Alesund Breast CT')
clips_r = ROI.ROIDLS('Clips_R', 'Marker', COLORS.clips, 'St. Olavs-Alesund Breast CT')
coccyx = ROI.ROIDLS('Coccyx', 'Organ', COLORS.bone_color2, 'Alesund Male Pelvic CT')
cochlea_l = ROI.ROIDLS('Cochlea_L','Organ', COLORS.cochlea, 'RSL DLS CT')
cochlea_r = ROI.ROIDLS('Cochlea_R','Organ', COLORS.cochlea, 'RSL DLS CT')
esophagus = ROI.ROIDLS('Esophagus', 'Organ', COLORS.esophagus, 'RSL DLS CT')
eye_l = ROI.ROIDLS('Eye_L', 'Organ', COLORS.eye, 'RSL DLS CT')
eye_r = ROI.ROIDLS('Eye_R', 'Organ', COLORS.eye, 'RSL DLS CT')
femoral_head_l = ROI.ROIDLS('FemoralHead_L', 'Organ', COLORS.femoral, 'RSL DLS CT', lib_name = 'Femur_Head_L')
femoral_head_r = ROI.ROIDLS('FemoralHead_R', 'Organ', COLORS.femoral, 'RSL DLS CT', lib_name = 'Femur_Head_R')
femur_l = ROI.ROIDLS('Femur_L', 'Organ', COLORS.bone_color1, 'Alesund Male Pelvic CT', lib_name = 'FemurHeadNeck_L')
femur_r = ROI.ROIDLS('Femur_R', 'Organ', COLORS.bone_color1, 'Alesund Male Pelvic CT', lib_name = 'FemurHeadNeck_R')
heart = ROI.ROIDLS('Heart', 'Organ', COLORS.heart, 'RSL DLS CT', lib_name = 'Heart_pa_separate')
humeral_head_l = ROI.ROIDLS('HumeralHead_L', 'Organ', COLORS.bone_color1, 'RSL DLS CT')
humeral_head_r = ROI.ROIDLS('HumeralHead_R', 'Organ', COLORS.bone_color1, 'RSL DLS CT')
iliopsoas_muscle_l = ROI.ROIDLS('IliopsoasMuscle_L', 'Organ', COLORS.muscle, 'Alesund Male Pelvic CT')
iliopsoas_muscle_r = ROI.ROIDLS('IliopsoasMuscle_R', 'Organ', COLORS.muscle, 'Alesund Male Pelvic CT')
kidney_l = ROI.ROIDLS('Kidney_L', 'Organ', COLORS.kidney, 'Alesund Male Pelvic CT')
kidney_r = ROI.ROIDLS('Kidney_R', 'Organ', COLORS.kidney, 'Alesund Male Pelvic CT')
l2 = ROI.ROIDLS('L2', 'Organ', COLORS.bone_color1, 'Alesund Male Pelvic CT')
l3 = ROI.ROIDLS('L3', 'Organ', COLORS.bone_color2, 'Alesund Male Pelvic CT')
l4 = ROI.ROIDLS('L4', 'Organ', COLORS.bone_color1, 'Alesund Male Pelvic CT')
l5 = ROI.ROIDLS('L5', 'Organ', COLORS.bone_color2, 'Alesund Male Pelvic CT')
lacrimal_l = ROI.ROIDLS('LacrimalGland_L', 'Organ', COLORS.lacrimal, 'RSL DLS CT')
lacrimal_r = ROI.ROIDLS('LacrimalGland_R', 'Organ', COLORS.lacrimal, 'RSL DLS CT')
lens_l = ROI.ROIDLS('Lens_L', 'Organ', COLORS.lens, 'RSL DLS CT')
lens_r = ROI.ROIDLS('Lens_R', 'Organ', COLORS.lens, 'RSL DLS CT')
liver = ROI.ROIDLS('Liver','Organ', COLORS.liver, 'Alesund Male Pelvic CT')
ln_ax_l1_l = ROI.ROIDLS('LN_Ax_L1_L', 'Organ', COLORS.level1, 'RSL DLS CT')
ln_ax_l1_r = ROI.ROIDLS('LN_Ax_L1_R', 'Organ', COLORS.level1, 'RSL DLS CT')
ln_ax_l2_l = ROI.ROIDLS('LN_Ax_L2_L', 'Organ', COLORS.level2, 'RSL DLS CT')
ln_ax_l2_r = ROI.ROIDLS('LN_Ax_L2_R', 'Organ', COLORS.level2, 'RSL DLS CT')
ln_ax_l3_l = ROI.ROIDLS('LN_Ax_L3_L', 'Organ', COLORS.level3, 'RSL DLS CT')
ln_ax_l3_r = ROI.ROIDLS('LN_Ax_L3_R', 'Organ', COLORS.level3, 'RSL DLS CT')
ln_ax_l4_l = ROI.ROIDLS('LN_Ax_L4_L', 'Organ', COLORS.level4, 'RSL DLS CT')
ln_ax_l4_r = ROI.ROIDLS('LN_Ax_L4_R', 'Organ', COLORS.level4, 'RSL DLS CT')
ln_ax_pectoral_l = ROI.ROIDLS('LN_Ax_Pectoral_L', 'Organ', COLORS.level, 'RSL DLS CT')
ln_ax_pectoral_r = ROI.ROIDLS('LN_Ax_Pectoral_R', 'Organ', COLORS.level, 'RSL DLS CT')
ln_imn_l = ROI.ROIDLS('LN_IMN_L', 'Organ', COLORS.imn, 'RSL DLS CT')
ln_imn_r = ROI.ROIDLS('LN_IMN_R', 'Organ', COLORS.imn, 'RSL DLS CT')
lung_l =  ROI.ROIDLS('Lung_L', 'Organ', COLORS.lung, 'RSL DLS CT')
lung_r =  ROI.ROIDLS('Lung_R', 'Organ', COLORS.lung, 'RSL DLS CT')
optic_chiasm = ROI.ROIDLS('OpticChiasm','Organ', COLORS.chiasma, 'RSL DLS CT')
optic_nerve_l = ROI.ROIDLS('OpticNerve_L', 'Organ', COLORS.optic_nrv, 'RSL DLS CT')
optic_nerve_r = ROI.ROIDLS('OpticNerve_R', 'Organ', COLORS.optic_nrv, 'RSL DLS CT')
oral_cavity = ROI.ROIDLS('OralCavity', 'Organ', COLORS.oral_cavity, 'RSL DLS CT')
pancreas = ROI.ROIDLS('Pancreas','Organ', COLORS.pancreas, 'RSL DLS CT')
parotid_l = ROI.ROIDLS('Parotid_L', 'Organ', COLORS.parotid, 'RSL DLS CT', lib_name = 'ParotidGland_L')
parotid_r = ROI.ROIDLS('Parotid_R', 'Organ', COLORS.parotid, 'RSL DLS CT', lib_name = 'ParotidGland_R')
pelvic_girdle_l = ROI.ROIDLS('PelvicGirdle_L', 'Organ', COLORS.bone_color3, 'Alesund Male Pelvic CT')
pelvic_girdle_r = ROI.ROIDLS('PelvicGirdle_R', 'Organ', COLORS.bone_color3, 'Alesund Male Pelvic CT')
pelvic_nodes = ROI.ROIDLS('LN_Iliac', 'Organ', COLORS.pelvic_nodes, 'Alesund Male Pelvic CT')
penile_bulb = ROI.ROIDLS('PenileBulb', 'Organ', COLORS.penile_bulb, 'Alesund Male Pelvic CT')
pituitary = ROI.ROIDLS('Pituitary', 'Organ', COLORS.pituitary, 'RSL DLS CT')
prostate = ROI.ROIDLS('Prostate', 'Organ', COLORS.prostate, 'RSL DLS CT', lib_name = 'Prostate_minus_VenousPlexus')
rectum = ROI.ROIDLS('Rectum', 'Organ', COLORS.rectum, 'Alesund Male Pelvic CT')
sacrum = ROI.ROIDLS('Sacrum', 'Organ', COLORS.bone_color1, 'Alesund Male Pelvic CT')
scalene_muscle_ant_l = ROI.ROIDLS('ScaleneMuscle_Ant_L', 'Organ', COLORS.muscle, 'RSL DLS CT', lib_name = 'M_Scalene_Ant_L')
scalene_muscle_ant_r = ROI.ROIDLS('ScaleneMuscle_Ant_R', 'Organ', COLORS.muscle, 'RSL DLS CT', lib_name = 'M_Scalene_Ant_R')
seminal_vesicles = ROI.ROIDLS('SeminalVes', 'Organ', COLORS.vesicles, 'RSL DLS CT', lib_name = 'SeminalVesicles')
spinal_canal = ROI.ROIDLS('SpinalCanal', 'Organ', COLORS.spinal_canal, 'RSL DLS CT')
spleen = ROI.ROIDLS('Spleen','Organ', COLORS.spleen, 'RSL DLS CT')
sternum = ROI.ROIDLS('Sternum', 'Organ', COLORS.bone_color3, 'RSL DLS CT')
stomach = ROI.ROIDLS('Stomach','Organ', COLORS.stomach, 'RSL DLS CT')
submand_l = ROI.ROIDLS('SubmandGland_L', 'Organ', COLORS.submand, 'RSL DLS CT', lib_name = 'SubmandibularGland_L')
submand_r = ROI.ROIDLS('SubmandGland_R', 'Organ', COLORS.submand, 'RSL DLS CT', lib_name = 'SubmandibularGland_R')
surgical_bed_l = ROI.ROIDLS('SurgicalBed_L','Target', COLORS.surgical_bed, 'St. Olavs-Alesund Breast CT')
surgical_bed_r = ROI.ROIDLS('SurgicalBed_R','Target', COLORS.surgical_bed, 'St. Olavs-Alesund Breast CT')
thyroid = ROI.ROIDLS('ThyroidGland','Organ', COLORS.thyroid, 'RSL DLS CT')
trachea = ROI.ROIDLS('Trachea','Organ', COLORS.trachea, 'RSL DLS CT', lib_name = 'Trachea_1cm_sup_carina')
v_brachiocephalic_l = ROI.ROIDLS('V_Brachiocephalic_L', 'Organ', COLORS.vein_color3, 'RSL DLS CT')
v_brachiocephalic_r = ROI.ROIDLS('V_Brachiocephalic_R', 'Organ', COLORS.vein_color3, 'RSL DLS CT')
v_common_iliac_l = ROI.ROIDLS('V_CommonIliac_L', 'Organ', COLORS.vein_color2, 'Alesund Male Pelvic CT')
v_common_iliac_r = ROI.ROIDLS('V_CommonIliac_R', 'Organ', COLORS.vein_color2, 'Alesund Male Pelvic CT')
v_external_iliac_l = ROI.ROIDLS('V_ExternalIliac_L', 'Organ', COLORS.vein_color4, 'Alesund Male Pelvic CT')
v_external_iliac_r = ROI.ROIDLS('V_ExternalIliac_R', 'Organ', COLORS.vein_color4, 'Alesund Male Pelvic CT')
v_inferior_vena_cava = ROI.ROIDLS('V_InferiorVenaCava', 'Organ', COLORS.vein_color1, 'Alesund Male Pelvic CT')
v_internal_iliac_l = ROI.ROIDLS('V_InternalIliac_L', 'Organ', COLORS.vein_color3, 'Alesund Male Pelvic CT')
v_internal_iliac_r = ROI.ROIDLS('V_InternalIliac_R', 'Organ', COLORS.vein_color3, 'Alesund Male Pelvic CT')
v_jugular_int_l = ROI.ROIDLS('V_Jugular_Int_L', 'Organ', COLORS.vein_color6, 'RSL DLS CT')
v_jugular_int_r = ROI.ROIDLS('V_Jugular_Int_R', 'Organ', COLORS.vein_color6, 'RSL DLS CT')
v_subclavian_l = ROI.ROIDLS('V_Subclavian_L', 'Organ', COLORS.vein_color2, 'RSL DLS CT')
v_subclavian_r = ROI.ROIDLS('V_Subclavian_R', 'Organ', COLORS.vein_color2, 'RSL DLS CT')
v_superior_vena_cava = ROI.ROIDLS('V_SuperiorVenaCava', 'Organ', COLORS.vein_color5, 'RSL DLS CT', lib_name = 'V_Cava_superior')


# Derived ROIs:
# Subtraction:
bowel_bag = ROI.ROIAlgebra('BowelBag', 'Organ', COLORS.bowel_space, sourcesA = [bowel_bag_draft], sourcesB = [bladder], operator = 'Subtraction', marginsA = MARGINS.zero, marginsB = MARGINS.zero)
bladder_derived = ROI.ROIAlgebra('Bladder', 'Organ', COLORS.bladder, sourcesA = [bladder_draft], sourcesB = [prostate], operator = 'Subtraction', marginsA = MARGINS.zero, marginsB = MARGINS.zero)
brainstem_core = ROI.ROIExpanded('BrainstemCore', 'Organ', COLORS.brainstem_core, brainstem, margins = MARGINS.uniform_2mm_contraction)
brainstem_surface = ROI.ROIAlgebra('BrainstemSurface', 'Organ', COLORS.brainstem_surface, sourcesA = [brainstem], sourcesB = [brainstem_core], operator = 'Subtraction')
# Expansion:
spinal_cord_prv = ROI.ROIExpanded('SpinalCord_PRV', 'Avoidance', COLORS.prv, source=spinal_cord, margins=MARGINS.uniform_2mm_expansion)
# Union:
breast_l = ROI.ROIAlgebra('Breast_L', 'Organ', COLORS.contralat, sourcesA = [breast_l_draft], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)
breast_r = ROI.ROIAlgebra('Breast_R', 'Organ', COLORS.contralat, sourcesA = [breast_r_draft], sourcesB = [external], operator = 'Intersection', marginsA = MARGINS.zero, marginsB = MARGINS.uniform_5mm_contraction)
bronchial_tree = ROI.ROIAlgebra('BronchialTree', 'Organ', COLORS.trachea, sourcesA = [trachea], sourcesB = [carina, bronchus_main_l, bronchus_main_r, bronchus_intermedius, bronchi_lobar_l, bronchi_lobar_r], operator = 'Union')
greatves = ROI.ROIAlgebra('GreatVessel', 'Organ', COLORS.a_pulmonary, sourcesA = [a_aortic_arch, a_ascending_aorta, a_descending_aorta], sourcesB = [v_inferior_vena_cava, v_superior_vena_cava], operator = 'Union')
kidneys =  ROI.ROIAlgebra('Kidneys', 'Organ', COLORS.kidneys, sourcesA=[kidney_l], sourcesB=[kidney_r])
lungs =  ROI.ROIAlgebra('Lungs', 'Organ', COLORS.lungs, sourcesA=[lung_l], sourcesB=[lung_r])
lungs_igtv = ROI.ROIAlgebra('Lungs-IGTV', 'Organ', COLORS.lungs, sourcesA=[lungs], sourcesB=[igtv], operator = 'Subtraction')
parotids = ROI.ROIAlgebra('Parotids', 'Organ', COLORS.parotid, sourcesA=[parotid_l], sourcesB=[parotid_r])
ribs_l = ROI.ROIAlgebra('Ribs_L','Organ', COLORS.ribs, sourcesA=[rib_x_l], sourcesB=[rib_y_l])
ribs_r = ROI.ROIAlgebra('Ribs_R','Organ', COLORS.ribs, sourcesA=[rib_x_r], sourcesB=[rib_y_r])
submands = ROI.ROIAlgebra('SubmandGlands', 'Organ', COLORS.submand, sourcesA=[submand_l], sourcesB=[submand_r])
# Wall:
skin = ROI.ROIWall('Skin','Organ', COLORS.skin, external, 0, 0.3)
skin_brain = ROI.ROIWall('Skin','Organ', COLORS.skin, external, 0, 0.5)
skin_brain_5 = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.5)
skin_srt = ROI.ROIWall('Skin','Organ', COLORS.skin, body, 0, 0.3)
wall_ptv = ROI.ROIWall('zPTV_Wall', 'Undefined', COLORS.wall, iptv, 1, 0)
wall_ptv1 = ROI.ROIWall('zPTV1_Wall', 'Undefined', COLORS.wall, iptv1, 1, 0)
wall_ptv2 = ROI.ROIWall('zPTV2_Wall', 'Undefined', COLORS.wall, iptv2, 1, 0)
wall_ptv3 = ROI.ROIWall('zPTV3_Wall', 'Undefined', COLORS.wall, iptv3, 1, 0)
z_eye_l = ROI.ROIWall('zEye_L','Undefined', COLORS.wall, eye_l, 0, 0.2)
z_eye_r = ROI.ROIWall('zEye_R','Undefined', COLORS.wall, eye_r, 0, 0.2)
